from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlacklistEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("term", models.CharField(max_length=200, unique=True)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["term"], "verbose_name_plural": "blacklist entries"},
        ),
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("profile_text", models.TextField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-version", "name"]},
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("referenznummer", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("titel", models.CharField(max_length=500)),
                ("firma", models.CharField(blank=True, max_length=300)),
                ("beruf", models.CharField(blank=True, max_length=300)),
                ("ort", models.CharField(blank=True, max_length=200)),
                ("plz", models.CharField(blank=True, max_length=20)),
                ("strasse", models.CharField(blank=True, max_length=300)),
                ("entfernung_km", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("vollzeit", models.BooleanField(blank=True, null=True)),
                ("homeoffice", models.BooleanField(blank=True, null=True)),
                ("stellenangebotsart", models.CharField(blank=True, max_length=100)),
                ("homeofficetyp", models.CharField(blank=True, max_length=100)),
                ("eintrittsdatum", models.DateField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="arbeitsagentur", max_length=50)),
                ("beschreibung", models.TextField(blank=True)),
                ("bewerbungslink", models.URLField(blank=True, max_length=1500)),
                ("description_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("description_hash", models.CharField(blank=True, max_length=64)),
                ("llm_score", models.FloatField(blank=True, null=True)),
                ("llm_pro", models.JSONField(blank=True, default=list)),
                ("llm_contra", models.JSONField(blank=True, default=list)),
                ("llm_model", models.CharField(blank=True, max_length=200)),
                ("llm_prompt_version", models.CharField(blank=True, max_length=50)),
                ("llm_scored_at", models.DateTimeField(blank=True, null=True)),
                ("buzzword_score", models.FloatField(blank=True, null=True)),
                ("buzzword_hits", models.JSONField(blank=True, default=list)),
                ("buzzword_scored_at", models.DateTimeField(blank=True, null=True)),
                ("score_divergence", models.FloatField(blank=True, null=True)),
                ("manual_review", models.BooleanField(default=False)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-first_seen"]},
        ),
        migrations.CreateModel(
            name="JobSearch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("was", models.CharField(blank=True, max_length=300)),
                ("wo", models.CharField(default="Berlin", max_length=200)),
                ("radius_km", models.PositiveIntegerField(default=50)),
                ("page_size", models.PositiveIntegerField(default=25)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobSyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("jobs_seen", models.PositiveIntegerField(default=0)),
                ("jobs_created", models.PositiveIntegerField(default=0)),
                ("jobs_updated", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("search", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sync_runs", to="tracker.jobsearch")),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_status", models.CharField(choices=[("applied", "Applied"), ("rejected", "Rejected"), ("interview_invited", "Interview invited"), ("interview_done", "Interview done"), ("offer", "Offer"), ("withdrawn", "Withdrawn")], default="applied", max_length=30)),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="tracker.job")),
            ],
            options={"ordering": ["-applied_at"]},
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(default="imap", max_length=50)),
                ("message_id", models.CharField(max_length=500, unique=True)),
                ("thread_id", models.CharField(blank=True, max_length=500)),
                ("sender", models.EmailField(blank=True, max_length=254)),
                ("recipients", models.TextField(blank=True)),
                ("subject", models.TextField(blank=True)),
                ("received_at", models.DateTimeField()),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                ("parsed", models.BooleanField(default=False)),
                ("classification", models.CharField(blank=True, max_length=100)),
                ("classification_confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("application", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="emails", to="tracker.application")),
            ],
            options={"ordering": ["-received_at"]},
        ),
        migrations.CreateModel(
            name="JobEvaluation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.FloatField()),
                ("pro", models.JSONField(blank=True, default=list)),
                ("contra", models.JSONField(blank=True, default=list)),
                ("model_name", models.CharField(max_length=200)),
                ("prompt_version", models.CharField(max_length=50)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluations", to="tracker.job")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluations", to="tracker.candidateprofile")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_type", models.CharField(choices=[("cover_letter", "Cover letter"), ("cv", "CV"), ("email", "Application email")], max_length=30)),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("model_name", models.CharField(blank=True, max_length=200)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("application", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="documents", to="tracker.application")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="tracker.job")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("status_changed", "Status changed"), ("auto_reply", "Auto reply"), ("email_received", "Email received"), ("interview_scheduled", "Interview scheduled"), ("interview_completed", "Interview completed"), ("note", "Note")], max_length=40)),
                ("status", models.CharField(blank=True, choices=[("applied", "Applied"), ("rejected", "Rejected"), ("interview_invited", "Interview invited"), ("interview_done", "Interview done"), ("offer", "Offer"), ("withdrawn", "Withdrawn")], max_length=30)),
                ("source", models.CharField(choices=[("manual", "Manual"), ("email_parsed", "Email parsed"), ("llm_classified", "LLM classified"), ("system", "System")], default="manual", max_length=30)),
                ("note", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("application", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="tracker.application")),
                ("email_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="application_events", to="tracker.emailmessage")),
            ],
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddIndex(model_name="job", index=models.Index(fields=["-first_seen"], name="tracker_job_first_s_20b6ca_idx")),
        migrations.AddIndex(model_name="job", index=models.Index(fields=["-llm_score"], name="tracker_job_llm_scor_4bbd9d_idx")),
        migrations.AddIndex(model_name="job", index=models.Index(fields=["firma"], name="tracker_job_firma_4a28b9_idx")),
        migrations.AddIndex(model_name="job", index=models.Index(fields=["ort"], name="tracker_job_ort_46b7c0_idx")),
        migrations.AddIndex(model_name="job", index=models.Index(fields=["manual_review"], name="tracker_job_manual__be4ce1_idx")),
        migrations.AddIndex(model_name="application", index=models.Index(fields=["current_status", "-applied_at"], name="tracker_applicat_status_8a19f5_idx")),
        migrations.AddIndex(model_name="emailmessage", index=models.Index(fields=["-received_at"], name="tracker_emailm_receive_4f1c8a_idx")),
        migrations.AddIndex(model_name="jobevaluation", index=models.Index(fields=["job", "-created_at"], name="tracker_jobeval_job_id_4a41b3_idx")),
        migrations.AddConstraint(model_name="applicationevent", constraint=models.UniqueConstraint(fields=("application", "email_message", "event_type"), name="uniq_application_email_event_type")),
    ]